name: lint


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop-1.9
      - develop
  workflow_dispatch:


permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        lint-command:
          - "pylint --j 2 --reports no datacube"
          - "--group types mypy datacube"
          - "pycodestyle tests integration_tests examples --max-line-length 120"

    name: Linting
    steps:
      - name: checkout git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
          enable-cache: 'true'
          cache-suffix: ${{ matrix.python-version }}
      - name: Run ${{ matrix.lint-command }}
        run: |
          uv run ${LINT_COMMAND}
        env:
          LINT_COMMAND: ${{matrix.lint-command}}
          UV_PYTHON: ${{ matrix.python-version }}
          UV_PYTHON_PREFERENCE: managed
